In [3]:
#I AM GOING TO BUILD A NEURAL NETWORK FROM SCRATCH THAT USES MNIST DATASET TO CLASSIFY HANDWRITTEN DIGITS

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
train_path = "C:/Users/mario/mnist_train.csv"
train_df = pd.read_csv(train_path)
data = np.array(train_df)

In [5]:
train_df.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [6]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [7]:
def init_params():
    W1 = np.random.randn(10, 784) * np.sqrt(2 / 784) 
    B1 = np.zeros((10, 1)) 
    W2 = np.random.randn(10, 10) * np.sqrt(2 / 10)
    B2 = np.zeros((10, 1))
    return W1, B1, W2, B2

def ReLU(Z):
    return np.maximum(0,Z)

def Softmax(Z):
    expZ = np.exp(Z - np.max(Z, axis=0, keepdims=True)) 
    return expZ / np.sum(expZ, axis=0, keepdims=True)

def forward_prop(W1,B1,W2,B2,X):
    Z1 = W1.dot(X) + B1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + B2
    A2 = Softmax(Z2)
    return Z1,A1,Z2,A2

def ReLU_d(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backprop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2, axis=1, keepdims=True)
    dZ1 = W2.T.dot(dZ2) * ReLU_d(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1, axis=1, keepdims=True)
    return dW1, db1, dW2, db2

def actualizar_parametros(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [8]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_dec(X,Y,iterations,alpha):
    W1,B1,W2,B2 = init_params()
    for i in range(iterations):
        Z1,A1,Z2,A2 = forward_prop(W1,B1,W2,B2,X)
        dW1, db1, dW2, db2 = backprop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, B1, W2, B2 = actualizar_parametros(W1, B1, W2, B2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteracion: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))

    return W1,B1,W2,B2

In [ ]:
W1,B1,W2,B2 = gradient_dec(X_train, Y_train, 500, 0.1) #90% accuracy. Not bad for a simple neural network. :D 

Iteracion:  0
[5 5 7 ... 5 5 2] [9 8 4 ... 3 5 1]
0.09830508474576272
Iteracion:  10
[2 8 4 ... 8 8 7] [9 8 4 ... 3 5 1]
0.3654406779661017
Iteracion:  20
[7 8 4 ... 8 8 7] [9 8 4 ... 3 5 1]
0.5090847457627119
Iteracion:  30
[7 8 4 ... 3 8 1] [9 8 4 ... 3 5 1]
0.631406779661017
Iteracion:  40
[9 8 4 ... 3 8 1] [9 8 4 ... 3 5 1]
0.714728813559322
Iteracion:  50
[9 8 4 ... 3 8 1] [9 8 4 ... 3 5 1]
0.7552033898305085
Iteracion:  60
[9 8 4 ... 3 8 1] [9 8 4 ... 3 5 1]
0.7829491525423729
Iteracion:  70
[9 8 4 ... 3 8 1] [9 8 4 ... 3 5 1]
0.8005762711864407
Iteracion:  80
[9 8 4 ... 3 8 1] [9 8 4 ... 3 5 1]
0.8145084745762712
Iteracion:  90
[9 8 4 ... 3 8 1] [9 8 4 ... 3 5 1]
0.825135593220339
Iteracion:  100
[9 8 4 ... 3 5 1] [9 8 4 ... 3 5 1]
0.8336779661016949
Iteracion:  110
[9 8 4 ... 3 5 1] [9 8 4 ... 3 5 1]
0.8406949152542373
Iteracion:  120
[9 8 4 ... 3 5 1] [9 8 4 ... 3 5 1]
0.8469152542372881
Iteracion:  130
[9 8 4 ... 3 5 1] [9 8 4 ... 3 5 1]
0.8523898305084746
Iteracion:  140
[9 

In [9]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()